import logging
import argparse
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.utils as utils
from evotorch import Problem
from evotorch.algorithms import GeneticAlgorithm
from evotorch.operators import SimulatedBinaryCrossOver, GaussianMutation

logging.getLogger("evotorch").setLevel(logging.WARNING)

# ─────────────────────────────────────────────────────────────
#  1.  Neural Network Definition
# ─────────────────────────────────────────────────────────────

class XORNet(nn.Module):
    """A configurable feedforward network: 2 inputs → hidden layer(s) → 1 output.

    Args:
        hidden:       Number of neurons in the single hidden layer (used only
                      when `hidden_sizes` is not given).
        activation:   Non-linearity to apply after each hidden layer.
                      One of 'tanh', 'sigmoid', or 'relu'.
        hidden_sizes: Optional list of hidden-layer sizes, e.g. [4, 4] for
                      two hidden layers of 4 neurons each. When given,
                      overrides `hidden`. Defaults to None, which is
                      equivalent to `hidden_sizes=[hidden]` (today's
                      single-hidden-layer architecture, unchanged). Pass
                      `hidden_sizes=[]` for zero hidden layers — a bare
                      linear classifier (Linear(2,1), no non-linearity) —
                      to directly test Part 1's "why can't hidden=0 solve
                      XOR" question empirically.
    """

    ACTIVATIONS = {
        "tanh":    nn.Tanh,
        "sigmoid": nn.Sigmoid,
        "relu":    nn.ReLU,
    }

    def __init__(self, hidden=3, activation="tanh", hidden_sizes=None):
        super().__init__()
        if activation not in self.ACTIVATIONS:
            raise ValueError(f"Unknown activation '{activation}'. Choose from {list(self.ACTIVATIONS)}")

        # Note: hidden_sizes=[] is intentionally valid (zero hidden layers,
        # i.e. a linear classifier) — only None falls back to [hidden].
        self.hidden_sizes = list(hidden_sizes) if hidden_sizes is not None else [hidden]

        layers = []
        in_dim = 2
        for h in self.hidden_sizes:
            layers.append(nn.Linear(in_dim, h))         # ... → hidden layer
            layers.append(self.ACTIVATIONS[activation]())  # non-linearity
            in_dim = h
        layers.append(nn.Linear(in_dim, 1))              # hidden layer → output neuron
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)


# ─────────────────────────────────────────────────────────────
#  2.  XOR Task — Inputs and Expected Signs
# ─────────────────────────────────────────────────────────────

XOR_INPUTS = torch.tensor([
    [0.0, 0.0],   # XOR(0,0) = 0  →  expected negative output
    [0.0, 1.0],   # XOR(0,1) = 1  →  expected positive output
    [1.0, 0.0],   # XOR(1,0) = 1  →  expected positive output
    [1.0, 1.0],   # XOR(1,1) = 0  →  expected negative output
], dtype=torch.float32)

XOR_SIGNS = torch.tensor([-1.0, 1.0, 1.0, -1.0])   # sign of correct output

# Alternate boolean tasks over the same 4 corner points (Part 3 "change the
# task" option). All share XOR_INPUTS; only the expected signs differ.
AND_SIGNS  = torch.tensor([-1.0, -1.0, -1.0,  1.0])
OR_SIGNS   = torch.tensor([-1.0,  1.0,  1.0,  1.0])
XNOR_SIGNS = torch.tensor([ 1.0, -1.0, -1.0,  1.0])

TASKS = {
    "xor":  (XOR_INPUTS, XOR_SIGNS),
    "and":  (XOR_INPUTS, AND_SIGNS),
    "or":   (XOR_INPUTS, OR_SIGNS),
    "xnor": (XOR_INPUTS, XNOR_SIGNS),
}


# ─────────────────────────────────────────────────────────────
#  2b. Random Problem Generator (Generalised XOR)
# ─────────────────────────────────────────────────────────────

def generate_random_problem(num_points=4, seed=None):
    """Generate a random binary classification problem similar to XOR.

    Each data point is generated by:
    - Sampling x, y from Uniform[-0.5, 1.5] (same range as XOR inputs)
    - Assigning a random sign (+1 or -1) with equal probability
    - The sign determines the expected output class

    Args:
        num_points: Number of data points to generate (default: 4).
        seed:       Optional random seed for reproducibility.

    Returns:
        A tuple (inputs, signs) where:
        - inputs: Tensor of shape (num_points, 2) with x, y coordinates
        - signs:  Tensor of shape (num_points,) with +1 or -1 for each point

    Example:
        >>> inputs, signs = generate_random_problem(num_points=10, seed=42)
        >>> # Use these in place of XOR_INPUTS / XOR_SIGNS
    """
    if seed is not None:
        torch.manual_seed(seed)
        np.random.seed(seed)

    # Sample x, y from uniform distribution [-0.5, 1.5]
    # This range centers around the same region as XOR inputs [0, 1]
    inputs = torch.rand(num_points, 2) * 2.0 - 0.5

    # Random signs: +1 or -1 with equal probability
    signs = torch.randint(0, 2, (num_points,), dtype=torch.float32) * 2 - 1

    return inputs, signs


# ─────────────────────────────────────────────────────────────
#  2c. Convex Problem Generator (Alternating Labels on a Circle)
# ─────────────────────────────────────────────────────────────

def generate_convex_problem(num_points=4):
    """Generate a convex-position binary classification problem.

    Points are placed on a circle (convex position) with alternating labels
    around the boundary. This generalises the XOR problem: XOR sits at the
    four corners of a square, and the alternating signs (-, +, -, +) make
    it non-linearly separable with a single hyperplane.

    With N points on a circle labeled alternately, you need N/2 hyperplanes
    to separate each arc of consecutive same-label points.

    This function is fully deterministic: it takes no seed because it takes
    no randomness — given the same num_points, it always returns the same
    points (unlike generate_random_problem, which does sample randomly).

    Args:
        num_points: Number of data points to generate (default: 4).

    Returns:
        A tuple (inputs, signs) where:
        - inputs: Tensor of shape (num_points, 2) with x, y coordinates
                  on a circle centered at (0.5, 0.5) with radius ~0.7
        - signs:  Tensor of shape (num_points,) with alternating +1, -1

    Example:
        >>> inputs, signs = generate_convex_problem(num_points=8)
        >>> # Use these in place of XOR_INPUTS / XOR_SIGNS
    """
    # Center the circle at (0.5, 0.5) with radius chosen to fit nicely
    # in the same region as XOR inputs [0, 1] x [0, 1]
    center = torch.tensor([0.5, 0.5])
    radius = 0.7

    # Generate angles evenly spaced around the circle
    # Starting from angle 0 and going counterclockwise
    # Note: PyTorch linspace doesn't have endpoint=False, so we use numpy then convert
    if num_points == 1:
        angles = torch.tensor([0.0])
    else:
        angles_np = np.linspace(0, 2 * np.pi, num_points, endpoint=False)
        angles = torch.from_numpy(angles_np.astype(np.float32))

    # Compute coordinates on the circle
    x_coords = center[0] + radius * torch.cos(angles)
    y_coords = center[1] + radius * torch.sin(angles)

    inputs = torch.stack([x_coords, y_coords], dim=-1)

    # Alternating signs: start with -1, then +1, -1, +1, ...
    # This matches XOR pattern: [-1, +1, +1, -1] for 4 points
    signs = torch.tensor([(-1) ** i for i in range(num_points)], dtype=torch.float32)

    return inputs, signs


# ─────────────────────────────────────────────────────────────
#  3.  Fitness Function
# ─────────────────────────────────────────────────────────────

def resolve_device(device_arg="auto"):
    """Resolve device string ('auto', 'cpu', 'cuda', 'mps', etc.) to a device string for PyTorch/EvoTorch."""
    if device_arg is None or device_arg == "auto":
        if torch.cuda.is_available():
            return "cuda"
        elif torch.backends.mps.is_available():
            return "mps"
        else:
            return "cpu"
    return device_arg


# Elementwise activation functions used by the vectorized fitness function.
# Must mirror XORNet.ACTIVATIONS so evolved genomes evaluate identically
# whether run through XORNet directly (e.g. in the plotting helpers) or
# through the batched fitness function below.
_ACTIVATION_FNS = {
    "tanh":    torch.tanh,
    "sigmoid": torch.sigmoid,
    "relu":    torch.relu,
}


def _genome_layout(hidden_sizes):
    """Sizes (in order) of each parameter block within a flat XORNet genome.

    Matches the order PyTorch's parameters_to_vector uses for
    nn.Sequential(Linear, Activation, Linear, Activation, ..., Linear):
    W1, b1, W2, b2, ..., W_n, b_n, walking the full dimension chain
    [2] + hidden_sizes + [1].

    Args:
        hidden_sizes: int (single hidden layer, today's behavior) or a
                      list of ints (one or more hidden layers).
    """
    if isinstance(hidden_sizes, int):
        hidden_sizes = [hidden_sizes]
    dims = [2] + list(hidden_sizes) + [1]
    layout = {}
    for i in range(len(dims) - 1):
        in_dim, out_dim = dims[i], dims[i + 1]
        layout[f"w{i + 1}"] = out_dim * in_dim
        layout[f"b{i + 1}"] = out_dim
    return layout


def genome_size(hidden=None, hidden_sizes=None):
    """Total genome length (weights + biases) for a given XORNet architecture.

    Computed analytically from `_genome_layout` rather than instantiating a
    throwaway `XORNet` just to count `p.numel()` over its parameters — the
    layout is architecture-only information, so there's no need to build the
    actual `nn.Module` to get its size.

    Args:
        hidden:       Number of neurons in the single hidden layer. Used only
                      when `hidden_sizes` is not given.
        hidden_sizes: Optional list of hidden-layer sizes, overriding `hidden`.

    Returns:
        Total number of weights + biases (int).
    """
    if hidden_sizes is None:
        if hidden is None:
            raise ValueError("genome_size: must supply either `hidden` or `hidden_sizes`")
        hidden_sizes = [hidden]
    else:
        hidden_sizes = list(hidden_sizes)
    return sum(_genome_layout(hidden_sizes).values())


def make_fitness_fn(hidden=None, activation="tanh", inputs=None, signs=None,
                     device=None, hidden_sizes=None, fitness_mode="sign"):
    """Return a *vectorized* fitness function for a batch of XORNet genomes.

    Instead of instantiating an nn.Module per genome (slow, and especially
    wasteful on GPU where each individual would otherwise trigger its own
    host<->device transfer), this reconstructs every individual's weight
    matrices directly from a batched genome tensor and evaluates the whole
    population in one shot using batched matrix multiplication. This is what
    makes `--device cuda`/`mps` actually pay off — a single big batched
    matmul is what GPUs are good at; thousands of tiny per-genome nn.Module
    calls are not. Supports an arbitrary number of hidden layers (via
    `hidden_sizes`) via a loop over layer boundaries, still with no
    per-individual Python loop — each layer is one batched einsum over the
    whole population.

    Args:
        hidden:       Number of hidden neurons (single hidden layer). Used
                      only when `hidden_sizes` is not given.
        activation:   Activation function name ('tanh', 'sigmoid', 'relu').
        inputs:       Optional custom input tensor. If None, uses XOR_INPUTS.
        signs:        Optional custom sign tensor. If None, uses XOR_SIGNS.
        device:       Target execution device ('cpu', 'cuda', 'mps', etc.).
        hidden_sizes: Optional list of hidden-layer sizes. Overrides `hidden`
                      when given; defaults to `[hidden]` otherwise (today's
                      exact single-hidden-layer behavior).
        fitness_mode: 'sign' (default) = fraction of points with the correct
                      output sign, exactly today's behavior. 'mse' = smooth
                      alternative: squash the output through tanh to (-1,1),
                      compute mean squared error against the +-1 signs
                      (range [0,4]), and return 1 - mse/4, clamped to [0,1]
                      so 1.0 still means "perfect" (needed for
                      run_neuroevolution's `best_fit >= 1.0` early-stop).

    Returns:
        A callable (genomes: Tensor[pop, n_genes]) -> Tensor[pop] suitable
        for EvoTorch's vectorized objective mode (Problem(..., vectorized=True)).
    """
    if hidden_sizes is None:
        if hidden is None:
            raise ValueError("make_fitness_fn: must supply either `hidden` or `hidden_sizes`")
        hidden_sizes = [hidden]
    else:
        hidden_sizes = list(hidden_sizes)

    if activation not in _ACTIVATION_FNS:
        raise ValueError(f"Unknown activation '{activation}'. Choose from {list(_ACTIVATION_FNS)}")
    if fitness_mode not in ("sign", "mse"):
        raise ValueError(f"Unknown fitness_mode '{fitness_mode}'. Choose from ('sign', 'mse')")
    act_fn = _ACTIVATION_FNS[activation]
    layout = _genome_layout(hidden_sizes)
    dims = [2] + hidden_sizes + [1]
    n_layers = len(dims) - 1

    # Use provided inputs/signs or fall back to default XOR data
    _inputs = inputs if inputs is not None else XOR_INPUTS
    _signs = signs if signs is not None else XOR_SIGNS
    if device is not None:
        _inputs = _inputs.to(device)
        _signs = _signs.to(device)

    def fitness_fn(genomes: torch.Tensor) -> torch.Tensor:
        """genomes: (pop, n_genes) -> fitness: (pop,)."""
        dev = genomes.device
        inputs_dev = _inputs.to(dev)   # (N, 2)
        signs_dev = _signs.to(dev)     # (N,)
        pop = genomes.shape[0]
        N = inputs_dev.shape[0]

        # activ starts as the input batch, broadcast across the population
        # dimension so every layer below uses one uniform einsum pattern
        # regardless of how many hidden layers there are.
        activ = inputs_dev.unsqueeze(0).expand(pop, N, dims[0])  # (pop, N, 2)

        offset = 0
        for i in range(1, n_layers + 1):
            in_dim, out_dim = dims[i - 1], dims[i]
            w = genomes[:, offset:offset + layout[f"w{i}"]].view(pop, out_dim, in_dim)
            offset += layout[f"w{i}"]
            b = genomes[:, offset:offset + layout[f"b{i}"]].view(pop, out_dim)
            offset += layout[f"b{i}"]

            # 'pnk,phk->pnh': per-individual (out_dim=h, in_dim=k) weights
            # applied to per-individual, per-point (n) activations.
            pre = torch.einsum("pnk,phk->pnh", activ, w) + b.unsqueeze(1)  # (pop, N, out_dim)
            activ = act_fn(pre) if i < n_layers else pre  # no activation on the final (output) layer

        output = activ.squeeze(-1)  # (pop, N), since final out_dim == 1

        if fitness_mode == "sign":
            correct = (output * signs_dev.unsqueeze(0) >= 0).float().sum(dim=1)  # (pop,)
            return correct / N  # normalised to [0, 1]
        else:  # "mse"
            pred = torch.tanh(output)                                       # squash to (-1, 1)
            mse = ((pred - signs_dev.unsqueeze(0)) ** 2).mean(dim=1)         # (pop,), in [0, 4]
            return (1.0 - mse / 4.0).clamp(0.0, 1.0)

    return fitness_fn


def parse_args():
    parser = argparse.ArgumentParser(description="Evolve a neural network controller for XOR.")
    parser.add_argument("--hidden",     type=int,   default=3,
                        help="Number of hidden neurons (default: 3)")
    parser.add_argument("--popsize",    type=int,   default=100,
                        help="Population size (default: 100)")
    parser.add_argument("--gens",       type=int,   default=200,
                        help="Number of generations (default: 200)")
    parser.add_argument("--mut_stdev",  type=float, default=0.5,
                        help="Gaussian mutation standard deviation (default: 0.5)")
    parser.add_argument("--activation", type=str,   default="tanh",
                        choices=["tanh", "sigmoid", "relu"],
                        help="Hidden layer activation function (default: tanh)")
    parser.add_argument("--vizperf",   action="store_true",
                        help="Plot fitness over generations")
    parser.add_argument("--vizbound",  action="store_true",
                        help="Plot the decision boundary of the best evolved network")
    parser.add_argument("--verbose",   action="store_true",
                        help="Print per-generation statistics to console")
    parser.add_argument("--seed",      type=int,   default=None,
                        help="Random seed for reproducibility")
    parser.add_argument("--random",    type=int,   default=None,
                        help="Number of random data points to use instead of XOR (default: None)")
    parser.add_argument("--convex",    type=int,   default=None,
                        help="Number of convex-position data points (on a circle, alternating labels)")
    parser.add_argument("--device",    type=str,   default="auto",
                        help="Execution device: 'auto', 'cpu', 'cuda', 'mps', etc. (default: auto)")
    parser.add_argument("--tournament_size", type=int, default=3,
                        help="Tournament size for SBX crossover (default: 3)")
    parser.add_argument("--eta",       type=float, default=20,
                        help="Distribution index for SBX crossover (default: 20)")
    parser.add_argument("--no-elitism", action="store_false", dest="elitism",
                        help="Disable elitism (best individual always survives by default)")
    parser.add_argument("--output",    type=str,   default=None,
                        help="File path to save the best evolved genome, e.g. best_genome.npy")
    parser.add_argument("--fitness_output", type=str, default=None,
                        help="Save per-generation best/avg/worst fitness to this .npz file "
                             "(keys: 'best', 'avg', 'worst'), so runs from different "
                             "configurations can be reloaded and compared later without "
                             "re-running evolution.")
    parser.add_argument("--seed_genome", type=str, default=None,
                        help="Path to a genome saved by a previous --output run (must match "
                             "the current --hidden/--activation architecture). Seeds the "
                             "initial population around this genome instead of starting from "
                             "scratch, to continue/restart evolution from a previous best "
                             "result.")
    parser.add_argument("--seed_noise", type=float, default=0.05,
                        help="Stdev of the Gaussian perturbation applied to --seed_genome "
                             "copies that fill out the rest of the initial population (one "
                             "individual is kept as an exact, unperturbed copy of the seed). "
                             "Ignored if --seed_genome isn't given.")
    parser.add_argument("--hidden_sizes", type=int, nargs="+", default=None,
                        help="List of hidden layer sizes, e.g. --hidden_sizes 4 4 for two "
                             "hidden layers of 4 neurons each. Overrides --hidden when given "
                             "(default: None, meaning a single hidden layer of size --hidden).")
    parser.add_argument("--fitness_mode", type=str, default="sign", choices=["sign", "mse"],
                        help="Fitness function: 'sign' = fraction of points classified with "
                             "the correct sign (default), 'mse' = smooth 1 - normalized-MSE "
                             "fitness against the +-1 targets.")
    parser.add_argument("--task", type=str, default="xor", choices=["xor", "and", "or", "xnor"],
                        help="Boolean task truth table to solve when --random/--convex are "
                             "not given (default: xor).")
    parser.add_argument("--init_bounds", type=float, nargs=2, default=[-1.0, 1.0],
                        metavar=("LOW", "HIGH"),
                        help="Initial genome sampling bounds (default: -1.0 1.0).")
    parser.add_argument("--no-crossover", action="store_false", dest="use_crossover",
                        help="Disable SBX crossover, running a mutation-only GA. Default: "
                             "crossover enabled.")
    return parser.parse_args()


# ─────────────────────────────────────────────────────────────
#  4.  Neuroevolution Runner
# ─────────────────────────────────────────────────────────────

def run_neuroevolution(hidden=3, popsize=100, gens=200, mut_stdev=0.5,
                       activation="tanh", verbose=False, seed=None,
                       random_points=None, convex_points=None, device="auto",
                       inputs=None, signs=None, tournament_size=3, eta=20,
                       elitism=True, seed_genome_path=None, seed_noise=0.05,
                       hidden_sizes=None, fitness_mode="sign", task="xor",
                       init_bounds=(-1.0, 1.0), use_crossover=True):
    """Evolve a neural network controller for the XOR task or a random/convex problem.

    The genome encodes all weights and biases of XORNet as a flat real-valued
    vector.  A GeneticAlgorithm with SimulatedBinaryCrossOver and
    GaussianMutation is used to maximise the XOR fitness function.

    Args:
        hidden:         Number of hidden neurons in XORNet.
        popsize:        Number of individuals in the population.
        gens:           Number of generations to run.
        mut_stdev:      Standard deviation for Gaussian mutation.
        activation:     Activation function ('tanh', 'sigmoid', 'relu').
        verbose:        If True, print statistics every 20 generations.
        seed:           Random seed for reproducibility (seeds the EA only —
                        see `inputs`/`signs` below for controlling the problem).
        random_points:  If not None and inputs/signs are not provided, use a
                        random problem with this many points instead of XOR.
        convex_points:  If not None and inputs/signs are not provided, use a
                        convex-position problem with this many points on a circle.
        device:         Target device ('auto', 'cpu', 'cuda', 'mps', etc.).
        inputs:         Optional pre-generated input tensor. If provided (together
                        with `signs`), this exact problem instance is used instead
                        of generating a new one — lets callers (e.g. study.py) hold
                        the problem fixed across repeated runs so that variance
                        across runs reflects only the EA's own stochasticity, not
                        a different random problem each time.
        signs:          Optional pre-generated sign labels, paired with `inputs`.
        tournament_size: Tournament size for SBX crossover.
        eta:            Distribution index for SBX crossover.
        elitism:        If True, best individual always survives to next generation.
        seed_genome_path: Path to a genome saved by a previous --output run. If given,
                        seeds the initial population around this genome (one exact
                        copy plus the rest perturbed by `seed_noise`) instead of
                        starting from scratch.
        seed_noise:     Stdev of the Gaussian perturbation applied to seed_genome_path copies.
        hidden_sizes:   Optional list of hidden-layer sizes, e.g. [4, 4] for two hidden
                        layers. Overrides `hidden` when given (default: None, meaning
                        a single hidden layer of size `hidden`).
        fitness_mode:   'sign' (default, today's exact behavior) or 'mse' (smooth
                        alternative fitness). See make_fitness_fn for details.
        task:           Boolean task to solve ('xor', 'and', 'or', 'xnor') when no
                        explicit inputs/signs/random_points/convex_points are given
                        (default: 'xor', today's exact behavior).
        init_bounds:    (low, high) tuple for the EA's initial genome sampling range
                        (default: (-1.0, 1.0), today's exact behavior).
        use_crossover:  If False, run a mutation-only GA (SimulatedBinaryCrossOver
                        removed from the operator list). Default True.

    Returns:
        best_fit        (np.ndarray): Best fitness at each generation.
        avg_fit         (np.ndarray): Average fitness at each generation.
        worst_fit       (np.ndarray): Worst fitness at each generation.
        best_genome     (torch.Tensor): Flat weight vector of the best individual.
        best_fitness    (float): Final best fitness value.
        inputs          (torch.Tensor): The input data used (XOR, random, or convex).
        signs           (torch.Tensor): The sign labels used (XOR, random, or convex).
        convergence_gen (int or None): Generation at which fitness first reached
                        1.0, or None if perfect fitness was never reached.
    """
    if seed is not None:
        torch.manual_seed(seed)
        np.random.seed(seed)

    target_device = resolve_device(device)
    if verbose:
        print(f"Using device: {target_device}")

    # Use a caller-supplied problem instance if given; otherwise generate one.
    if inputs is not None and signs is not None:
        pass
    elif convex_points is not None:
        inputs, signs = generate_convex_problem(num_points=convex_points)
    elif random_points is not None:
        inputs, signs = generate_random_problem(num_points=random_points, seed=seed)
    else:
        if task not in TASKS:
            raise ValueError(f"Unknown task '{task}'. Choose from {list(TASKS)}")
        inputs, signs = TASKS[task]

    fitness_fn = make_fitness_fn(hidden, activation, inputs=inputs, signs=signs,
                                  device=target_device, hidden_sizes=hidden_sizes,
                                  fitness_mode=fitness_mode)

    # Compute genome length analytically — no need to instantiate a network
    # just to count its parameters (see genome_size() above).
    n_genes = genome_size(hidden=hidden, hidden_sizes=hidden_sizes)

    problem = Problem(
        objective_sense="max",          # maximise fitness
        objective_func=fitness_fn,
        solution_length=n_genes,        # one gene per weight/bias
        initial_bounds=tuple(init_bounds),  # weights initialised in [low, high]
        dtype=torch.float32,
        device=target_device,
        vectorized=True,                # fitness_fn takes/returns whole-population batches
    )

    operators = []
    if use_crossover:
        # eta (SBX's "distribution index"): higher = offspring cluster
        # closer to their parents, lower = offspring spread further apart.
        # tournament_size: how many individuals compete for each parent
        # slot; higher = stronger pressure toward already-fit individuals.
        operators.append(SimulatedBinaryCrossOver(problem, tournament_size=tournament_size, eta=eta))
    operators.append(GaussianMutation(problem, stdev=mut_stdev))

    algorithm = GeneticAlgorithm(
        problem,
        popsize=popsize,
        operators=operators,
        elitist=elitism,   # best individual always survives → fitness never drops (default on)
    )

    # -- Seed the initial population, if requested --
    # GeneticAlgorithm builds its starting population in its constructor
    # (accessible as .population immediately, before the first .step()), so
    # overwriting it here applies before any evolution happens.
    if seed_genome_path is not None:
        seed_genome = torch.tensor(np.load(seed_genome_path), dtype=torch.float32, device=target_device)
        if seed_genome.numel() != n_genes:
            raise ValueError(
                f"Seed genome at '{seed_genome_path}' has {seed_genome.numel()} values, but "
                f"the current --hidden/--activation architecture expects {n_genes}. Make sure "
                f"these match what the seed genome was evolved with."
            )
        values = algorithm.population.access_values(keep_evals=False)
        values[0] = seed_genome  # one exact, unperturbed copy
        noise = torch.randn((popsize - 1, n_genes), device=target_device) * seed_noise
        values[1:] = seed_genome.unsqueeze(0) + noise

    best_fit  = np.zeros(gens)
    avg_fit   = np.zeros(gens)
    worst_fit = np.zeros(gens)
    convergence_gen = None  # generation perfect fitness was first reached (if any)

    for gen in range(gens):
        algorithm.step()

        fitnesses = algorithm.population.access_evals()[:, 0]
        # Replace any NaN values that may arise from bad mutations
        fitnesses = torch.where(torch.isnan(fitnesses), torch.zeros_like(fitnesses), fitnesses)

        best_fit[gen]  = fitnesses.max().item()
        avg_fit[gen]   = fitnesses.mean().item()
        worst_fit[gen] = fitnesses.min().item()

        if verbose and (gen % 10 == 0 or gen == gens - 1):
            pct = (fitnesses >= 1.0).float().mean().item() * 100
            print(f"Gen {gen:>4d} | Best: {best_fit[gen]:.4f} | "
                  f"Mean: {avg_fit[gen]:.4f} | Perfect: {int(pct)}%")

        # Early stopping once perfect fitness is found. Record the generation
        # this happened at *before* backfilling best_fit with 1.0s below —
        # otherwise that information is unrecoverable from best_fit alone.
        if best_fit[gen] >= 1.0:
            convergence_gen = gen
            if verbose:
                print(f"\nConverged at generation {gen}!")
            best_fit[gen:]  = 1.0
            avg_fit[gen:]   = avg_fit[gen]
            worst_fit[gen:] = worst_fit[gen]
            break

    # Retrieve the best genome
    fitnesses = algorithm.population.access_evals()[:, 0]
    fitnesses = torch.where(torch.isnan(fitnesses), torch.zeros_like(fitnesses), fitnesses)
    best_idx    = fitnesses.argmax().item()
    best_genome = algorithm.population.access_values()[best_idx].clone()
    best_fitness = fitnesses[best_idx].item()

    return best_fit, avg_fit, worst_fit, best_genome, best_fitness, inputs, signs, convergence_gen


# ─────────────────────────────────────────────────────────────
#  5.  Visualisation Helpers
# ─────────────────────────────────────────────────────────────

def plot_fitness(best_fit, avg_fit, worst_fit, problem_name="XOR"):
    """Plot best, average, and worst fitness over generations."""
    plt.figure(figsize=(10, 6))
    gens = np.arange(len(best_fit))
    plt.plot(gens, best_fit,  label="Best Fitness",  color="green", linewidth=2)
    plt.plot(gens, avg_fit,   label="Mean Fitness",  color="blue",  linewidth=2)
    plt.plot(gens, worst_fit, label="Worst Fitness", color="red",   linewidth=1, linestyle="--")
    plt.axhline(y=1.0, color="black", linestyle=":", alpha=0.5, label="Perfect (1.0)")
    plt.xlabel("Generation")
    plt.ylabel("Fitness")
    plt.title(f"Neuroevolution Performance — {problem_name} Controller")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.ylim(0, 1.05)
    plt.tight_layout()
    plt.show()


def plot_decision_boundary_custom(best_genome, hidden, activation, best_fitness,
                                   inputs, signs, problem_name="Custom", hidden_sizes=None):
    """Plot the 2-D decision boundary of the evolved network with custom data.

    Args:
        best_genome:  Flat weight vector of the best evolved network.
        hidden:       Number of hidden neurons (used only if hidden_sizes is None).
        activation:   Activation function name.
        best_fitness: Final best fitness value.
        inputs:       Input tensor (can be XOR, random, or convex).
        signs:        Sign labels (can be XOR, random, or convex).
        problem_name: Name to display in the title (e.g., "XOR", "Random(8)", "Convex(6)").
        hidden_sizes: Optional list of hidden-layer sizes, overriding `hidden`.
    """
    best_genome_cpu = best_genome.cpu()
    inputs_cpu = inputs.cpu()
    signs_cpu = signs.cpu()

    net = XORNet(hidden=hidden, activation=activation, hidden_sizes=hidden_sizes).to("cpu")
    utils.vector_to_parameters(best_genome_cpu, net.parameters())

    # ── Grid bounds: add 40 % padding around the actual data range ───────────
    pts_np = inputs_cpu.numpy()
    x_min, x_max = pts_np[:, 0].min(), pts_np[:, 0].max()
    y_min, y_max = pts_np[:, 1].min(), pts_np[:, 1].max()
    x_pad = max((x_max - x_min) * 0.4, 0.3)
    y_pad = max((y_max - y_min) * 0.4, 0.3)
    x_lo, x_hi = x_min - x_pad, x_max + x_pad
    y_lo, y_hi = y_min - y_pad, y_max + y_pad

    # ── Evaluate network on a fine grid ──────────────────────────────────────
    x_vals = torch.linspace(x_lo, x_hi, 300)
    y_vals = torch.linspace(y_lo, y_hi, 300)
    X_grid, Y_grid = torch.meshgrid(x_vals, y_vals, indexing="ij")
    points = torch.stack([X_grid.flatten(), Y_grid.flatten()], dim=-1)
    with torch.no_grad():
        output_map = net(points).view(300, 300).detach().numpy()

    fig, ax = plt.subplots(figsize=(7, 6))

    # Determine appropriate contour levels based on activation function
    # tanh outputs in [-1, 1], sigmoid in [0, 1]
    if activation == "sigmoid":
        # For sigmoid, decision boundary is at output=0.5
        levels_fill = [output_map.min(), 0.5, output_map.max()]
        colors = ["lightblue", "salmon"]
    else:
        # For tanh/relu, decision boundary is at output=0
        levels_fill = [output_map.min(), 0, output_map.max()]
        colors = ["lightblue", "salmon"]

    ax.contourf(X_grid.numpy(), Y_grid.numpy(), output_map,
                levels=levels_fill, colors=colors, alpha=0.5)
    ax.contour(X_grid.numpy(), Y_grid.numpy(), output_map,
               levels=[0] if activation != "sigmoid" else [0.5],
               colors=["black"], linewidths=1.5)

    # ── Scatter training points coloured by expected class ───────────────────
    signs_np = signs_cpu.numpy()
    pos_mask = signs_np > 0
    neg_mask = ~pos_mask

    if pos_mask.any():
        ax.scatter(pts_np[pos_mask, 0], pts_np[pos_mask, 1],
                   c="darkred", marker="x", s=200, linewidths=3,
                   label="Positive class", zorder=5)
    if neg_mask.any():
        ax.scatter(pts_np[neg_mask, 0], pts_np[neg_mask, 1],
                   c="darkblue", marker="o", facecolors="none",
                   s=150, linewidths=2.5, label="Negative class", zorder=5)

    # Use the provided problem name for the title
    if "XOR" in problem_name:
        title = f"Evolved Network — Decision Boundary\n"
        title += f"XOR (hidden={hidden}, activation={activation}, fitness={best_fitness:.4f})"
    else:
        title = f"Evolved Network — Decision Boundary\n"
        title += f"{problem_name} | hidden={hidden}, activation={activation}, fitness={best_fitness:.4f}"

    ax.set_xlim(x_lo, x_hi)
    ax.set_ylim(y_lo, y_hi)
    ax.set_xlabel("x₁")
    ax.set_ylabel("x₂")
    ax.set_aspect("equal")
    ax.legend(fontsize=10)
    ax.set_title(title)
    fig.tight_layout()
    plt.show()


def print_truth_table(best_genome, hidden, activation, hidden_sizes=None):
    """Print the XOR truth table produced by the evolved network."""
    best_genome_cpu = best_genome.cpu()
    net = XORNet(hidden=hidden, activation=activation, hidden_sizes=hidden_sizes).to("cpu")
    utils.vector_to_parameters(best_genome_cpu, net.parameters())

    with torch.no_grad():
        output = net(XOR_INPUTS)

    print("\n=== XOR Truth Table (Evolved Network) ===")
    print(f"{'x₁':>4}  {'x₂':>4}  | {'Output':>9}  | {'Expected':>8}  | {'Correct':>7}")
    print("-" * 50)
    for i, inp in enumerate(XOR_INPUTS):
        expected_sign = XOR_SIGNS[i].item()
        out_val = output[i].item()
        correct = (out_val * expected_sign >= 0)
        expected_str = "positive" if expected_sign > 0 else "negative"
        correct_str  = "✓" if correct else "✗"
        print(f"{inp[0].item():.0f}  {inp[1].item():.0f}  | {out_val:>9.4f}  | {expected_str:>8}  | {correct_str:>7}")

    perfect = all(
        (output[i].item() * XOR_SIGNS[i].item() >= 0) for i in range(4)
    )
    print(f"\nPerfect XOR controller: {perfect}")


def print_truth_table_custom(best_genome, hidden, activation, inputs, signs, hidden_sizes=None):
    """Print the truth table produced by the evolved network for custom data.

    Args:
        best_genome:  Flat weight vector of the best evolved network.
        hidden:       Number of hidden neurons (used only if hidden_sizes is None).
        activation:   Activation function name.
        inputs:       Input tensor (can be XOR or random).
        signs:        Sign labels (can be XOR or random).
        hidden_sizes: Optional list of hidden-layer sizes, overriding `hidden`.
    """
    best_genome_cpu = best_genome.cpu()
    inputs_cpu = inputs.cpu()
    signs_cpu = signs.cpu()

    net = XORNet(hidden=hidden, activation=activation, hidden_sizes=hidden_sizes).to("cpu")
    utils.vector_to_parameters(best_genome_cpu, net.parameters())

    with torch.no_grad():
        output = net(inputs_cpu)

    # Determine problem type for header
    if inputs is XOR_INPUTS:
        print("\n=== XOR Truth Table (Evolved Network) ===")
    else:
        print(f"\n=== Custom Problem ({len(inputs_cpu)} points) ===")

    print(f"{'x₁':>6}  {'x₂':>6}  | {'Output':>9}  | {'Expected':>8}  | {'Correct':>7}")
    print("-" * 50)

    correct_count = 0
    for i, inp in enumerate(inputs_cpu):
        expected_sign = signs_cpu[i].item()
        out_val = output[i].item()
        correct = (out_val * expected_sign >= 0)
        expected_str = "positive" if expected_sign > 0 else "negative"
        correct_str  = "✓" if correct else "✗"
        print(f"{inp[0].item():.2f}  {inp[1].item():.2f}  | {out_val:>9.4f}  | {expected_str:>8}  | {correct_str:>7}")
        if correct:
            correct_count += 1

    print(f"\nCorrect classifications: {correct_count}/{len(inputs_cpu)}")


# ─────────────────────────────────────────────────────────────
#  6.  Main Entry Point
# ─────────────────────────────────────────────────────────────

def main():
    """Command-line entry point for neuroevolution experiments (XOR / random / convex).

    Parses CLI arguments, runs neuroevolution with the selected configuration,
    and optionally plots fitness curves and decision boundaries.
    """
    args = parse_args()

    # Determine which problem to use
    if args.convex is not None:
        print(f"Evolving neural network on convex problem: "
              f"{args.convex} points on circle (alternating labels), hidden={args.hidden}, "
              f"activation={args.activation}, popsize={args.popsize}, gens={args.gens}")
    elif args.random is not None:
        print(f"Evolving neural network on random problem: "
              f"{args.random} points, hidden={args.hidden}, "
              f"activation={args.activation}, popsize={args.popsize}, gens={args.gens}")
    else:
        print(f"Evolving {args.task.upper()} controller: hidden={args.hidden}, "
              f"activation={args.activation}, popsize={args.popsize}, gens={args.gens}")

    if args.seed_genome:
        print(f"Seeding initial population from: {args.seed_genome} (seed_noise={args.seed_noise})")

    best_fit, avg_fit, worst_fit, best_genome, best_fitness, inputs, signs, convergence_gen = run_neuroevolution(
        hidden=args.hidden,
        popsize=args.popsize,
        gens=args.gens,
        mut_stdev=args.mut_stdev,
        activation=args.activation,
        verbose=args.verbose,
        seed=args.seed,
        random_points=args.random,
        convex_points=args.convex,
        device=args.device,
        tournament_size=args.tournament_size,
        eta=args.eta,
        elitism=args.elitism,
        seed_genome_path=args.seed_genome,
        seed_noise=args.seed_noise,
        hidden_sizes=args.hidden_sizes,
        fitness_mode=args.fitness_mode,
        task=args.task,
        init_bounds=tuple(args.init_bounds),
        use_crossover=args.use_crossover,
    )

    print(f"\nBest fitness achieved: {best_fitness:.4f}")
    if convergence_gen is not None:
        print(f"Converged at generation: {convergence_gen}")
    else:
        print(f"Did not reach perfect fitness within {args.gens} generations")

    if args.output:
        np.save(args.output, best_genome.cpu().numpy())
        print(f"Best genome saved to: {args.output}")

    if args.fitness_output:
        np.savez(args.fitness_output, best=best_fit, avg=avg_fit, worst=worst_fit)
        print(f"Fitness-over-generations saved to: {args.fitness_output}")

    print_truth_table_custom(best_genome, hidden=args.hidden, activation=args.activation,
                             inputs=inputs, signs=signs, hidden_sizes=args.hidden_sizes)

    # Determine problem name for display
    if args.convex is not None:
        problem_name = f"Convex({args.convex})"
    elif args.random is not None:
        problem_name = f"Random({args.random})"
    else:
        problem_name = args.task.upper()

    if args.vizperf:
        plot_fitness(best_fit, avg_fit, worst_fit, problem_name=problem_name)

    if args.vizbound:
        plot_decision_boundary_custom(best_genome, args.hidden, args.activation,
                                      best_fitness, inputs, signs, problem_name=problem_name,
                                      hidden_sizes=args.hidden_sizes)


if __name__ == "__main__":
    main()
